# Generated by Django 5.0.6 on 2024-06-21 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_alter_post_content_alter_post_likes_feed_friendship_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Workplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=6),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='educations',
            field=models.ManyToManyField(blank=True, related_name='user_profiles', to='social.education'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='workplaces',
            field=models.ManyToManyField(blank=True, related_name='user_profiles', to='social.workplace'),
        ),
    ]
