# Generated by Django 5.0.6 on 2024-06-24 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_userprofile_current_town_userprofile_education_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='work',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
