# Generated by Django 5.0.6 on 2024-06-23 13:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('social', '0003_alter_userprofile_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')],
                                   max_length=6),
        ),
    ]
