# Generated by Django 5.0.6 on 2024-06-24 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_post_name_post_tag_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
    ]
