# Generated by Django 5.0.6 on 2024-06-24 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0009_alter_post_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='name',
        ),
    ]
