# Generated by Django 5.0.6 on 2024-06-27 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0010_remove_post_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_logout',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
