# Generated by Django 5.0.6 on 2024-06-27 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0011_userprofile_last_logout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='last_logout',
        ),
    ]
