# Generated by Django 5.0.6 on 2024-06-27 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0011_userprofile_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(default='default.jpg', upload_to='profile_pictures/'),
        ),
    ]
