# Generated by Django 5.0.6 on 2024-07-02 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0012_remove_userprofile_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='education',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='work',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
